title: Yaodong's Homepage
page-top-title: Yaoodong
top-section-bg-text: Be what you wanna be
home-subtitle: Yaodong&ensp;|&ensp;Zhuyaodong
copyright-text: '&copy; Zhuyaodong 2023-2025. All Rights Reserved.'
